# Generated by Django 4.2.4 on 2023-09-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='превью (картинка)')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='main/', verbose_name='превью (картинка)')),
                ('link_video', models.CharField(max_length=150, verbose_name='ссылка на видео')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='дата оплаты')),
                ('payment_amount', models.SmallIntegerField(null=True, verbose_name='сумма оплаты')),
                ('method_pay', models.CharField(choices=[('transfer', 'наличные'), ('cash', 'перевод на счет')], max_length=15, verbose_name='способ оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='статус оплаты')),
                ('session', models.CharField(blank=True, max_length=250, null=True, verbose_name='сессия оплаты')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updates', models.CharField(choices=[('update_user', 'пользователь подписан на обновления'), ('not_updat_user', 'пользователь  не подписан на обновления')], max_length=15, verbose_name='признак обновление')),
                ('subscription', models.CharField(choices=[('install', 'у пользователя есть подписка на курс'), ('delete', 'у пользователя отсутствует подписка на курс')], max_length=15, verbose_name='признак подписки')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
