# Generated by Django 4.2.4 on 2023-09-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='статус оплаты'),
        ),
        migrations.AddField(
            model_name='pay',
            name='session',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='сессия оплаты'),
        ),
    ]
